steps:
  build:
    image: alvrme/alpine-android:android-34-jdk11
    commands:
      - apk add --no-cache python3
      - ./gradlew :app:assembleRelease
    when:
      path: [ app/**, build.gradle ]
  sign:
    image: alvrme/alpine-android:android-34-jdk11
    commands:
      - ./scripts/apk-sign.sh Eternity-signed.apk app/build/outputs/apk/release/app-release-unsigned.apk
    secrets: [ APK_KS_PASS, APK_KS, APK_KS_ALIAS ]
    when:
      event: [ tag ]
  publish:
    image: woodpeckerci/plugin-gitea-release
    settings:
      base_url: https://codeberg.org
      files:
        - Eternity-signed.apk
      api_key:
        from_secret: GITEA_ACCESS_TOKEN
      target: main
      prerelease: true
      note: "Pending release notes..."
    when:
      event: [ tag ]
when:
  event: [ push, tag, pull_request ]
